baseurl = ""
languageCode = "en-us"
title = "Statsmatter 3D AR/VR"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Vipul Pandey"
	description = "3D Artist"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Darpn"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "360, Virtual 3D and GIS Solutions"
		subtitle   = "Using [3D Virtual Mapping Solutions](https://sketchfab.com/Vipul.Pandey) Make your physical structures available for the virtual world and market your virtual tours !!"
		buttonText = "Find out more"


	# About section [Lorem](//google.com)
	[params.about]
		headline    = "We take your Business to 3D digital world!"
		description = " Get virtual tours created for your projects, and market it to the buyers through intelligent marketing "
		buttonText2  = "Social Media"
		

	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "360 vitual tours"
            description = "We create vitual tours for your projects, using VR Technology."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Photogrammetry"
			description = "Get 3D mappings done with tools of Photogrammetry "

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Digital realism in GIS"
            description = "We use lates tools and techniques to map 3d scanned models on GIS"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Targeted Marketing"
            description = "Find your buyers on digital platforms and show your virtual projects !"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get your demo tours made !!"

		[params.aside.button]
			text = "View demos"
			link = "https://www.youtube.com/channel/UCcIyf08zysh02qV_tkI0nQQ"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch !"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+91 7620552402"
		email = "statsmatterin@gmail.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
